### ISSUE TITLE
Not working with React 17.0.2

### ISSUE THREAD

**Issue by arudrakalyan** [bhubr/react-simple-oauth2-login#49]
npm i react-simple-oauth2-login
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gopi@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-simple-oauth2-login@0.5.1
npm ERR! node_modules/react-simple-oauth2-login
npm ERR!   react-simple-oauth2-login@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by bhubr** [comment]
Hello @arudrakalyan 

Thank you for reporting the issue. I've been off for a while, but now I'm gonna have some time to investigate it.

**Comment by bhubr** [comment]
Hi again @arudrakalyan 

I just pushed changes and republished the package (latest version is now 0.5.2).

 Would you be kind enough to let me know if that fixed your issue?
 Again, thank you for reporting, it's quite a critical issue and I'll try and be more cautious in the future.
 I've added you to the contributors list (if you don't mind!).
 
 Cheers

**Comment by arudrakalyan** [comment]
Hi @bhubr,

the issue is resolved.  You are a lifesaver :)
